### ISSUE TITLE
Mobile - Unexpected app crash while testing

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#47]
While quickly rifling through the pages and switching between Organizer, Sponsor, and Attendee (unfortunately might be difficult to repro again), the app suddenly crashed with only the following error and stack trace displayed in the running terminal:
```javascript
C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\ws\lib\WebSocket.js:219
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\ws\lib\WebSocket.js:219:16)
    at sendFn (C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\lib\attachWebsocketServer.js:75:21)
    at C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:134:29
    at Array.forEach (<anonymous>)
    at send (C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:134:11)
    at C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:363:7
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:72:24)
    at _next (C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:92:9)
    at C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:97:7
    at new Promise (<anonymous>)
    at C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:89:12
    at HmrServer._handleFileChange (C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\HmrServer.js:380:7)
    at C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\lib\debounceAsyncQueue.js:60:25
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile\node_modules\metro\src\lib\debounceAsyncQueue.js:15:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Version information:
```powershell
C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile>node --version
v15.9.0

C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile>npm --version
7.5.3

C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile>yarn --version
1.16.0

C:\Users\Sujan Kandeepan\Documents\COMPSCI 4ZP6\capstone\mobile>expo --version
4.1.6
```
Desktop: Windows 10 Home 20H2 build 19042.844
Mobile: Android 11 build RQ1A.210205.004

Severity: High
Priority: High

**Comment by enricoflorentino** [comment]
Was not able to reproduce but will keep this in mind
